"""
agents/test_generator.py
TestGenerator agent — automatically generates pytest test skeletons from subtask
descriptions without depending on the Anthropic SDK.

Behaviour:
    1. Parse subtask description for Python module/function/class references.
    2. Generate pytest test skeleton (test class + methods) using heuristics.
    3. Support multiple test patterns: functions, classes, API endpoints, CLI commands.
    4. Return generated test code as a string for inspection/writing.
"""

import os
import re
from typing import Any, Dict, List, Optional, Tuple


class SkeletonGenerator:
    """
    Generates pytest test skeletons from subtask descriptions.

    Does NOT depend on the Anthropic SDK. Uses template-based generation
    with heuristics to infer test patterns from description and output.

    Pattern detection:
        - "function" or "def " → test_xxx_function
        - "class" or "class " → test_xxx_class (with setUp/tearDown)
        - "/api", "/health", "GET /", "POST /" → test_xxx_endpoint (Flask test client)
        - "command", "CLI", "--flag" → test_xxx_command (subprocess/mock pattern)
        - Default → test_xxx_basic
    """

    # Regex patterns for detection
    _FUNCTION_RE = re.compile(
        r'(?:def\s+|function\s+|fn\s+)(\w+)', re.IGNORECASE
    )
    _CLASS_RE = re.compile(
        r'(?:class\s+)(\w+)', re.IGNORECASE
    )
    _ENDPOINT_RE = re.compile(
        r'(?:GET|POST|PUT|DELETE|PATCH)\s+/|\s+/[a-z]', re.IGNORECASE
    )
    _COMMAND_RE = re.compile(
        r'(?:command|cli|--[\w-]+|subprocess)', re.IGNORECASE
    )

    def __init__(self, settings: Optional[Dict[str, Any]] = None) -> None:
        cfg = settings or {}
        self._root = cfg.get("TEST_GENERATOR_ROOT", os.path.dirname(
            os.path.dirname(os.path.abspath(__file__))
        ))

    def generate_test(
        self,
        description: str,
        output: str = "",
        module_path: str = "",
    ) -> str:
        """
        Generate a pytest test skeleton from description and optional output.

        Args:
            description: Task description (e.g., "Create a function to parse JSON")
            output: Optional executor output (e.g., code snippet, file path)
            module_path: Optional module path (e.g., "utils/parser.py")

        Returns:
            Generated test code as a string (valid Python).
        """
        description = (description or "").strip()
        output = (output or "").strip()
        module_path = (module_path or "").strip()

        # Infer test type and target names from description + output
        test_type = self._detect_test_type(description, output)
        test_class, test_methods = self._infer_test_structure(
            description, output, module_path, test_type
        )

        # Generate imports based on detected type
        imports = self._generate_imports(test_type, module_path)

        # Generate test class with methods
        test_code = self._generate_test_class(
            test_class, test_methods, test_type, module_path
        )

        # Assemble: comment + imports + test code
        full_code = (
            "# auto-generated by TestGenerator\n"
            "\n"
            f"{imports}\n"
            "\n"
            f"{test_code}\n"
        )

        return full_code.strip() + "\n"

    def suggest_test_file(self, module_path: str) -> str:
        """
        Suggest a test file path for a given module path.

        Examples:
            "utils/parser.py" → "tests/test_parser.py"
            "api/app.py" → "api/test_app.py"
            "src/module.py" → "tests/test_module.py"
        """
        module_path = (module_path or "").strip()
        if not module_path:
            return "tests/test_generated.py"

        # Normalize path to forward slashes
        module_path = module_path.replace("\\", "/")

        # Extract filename without .py
        filename = os.path.basename(module_path)
        if filename.endswith(".py"):
            filename = filename[:-3]

        # Avoid double "test_" prefix
        if not filename.startswith("test_"):
            filename = f"test_{filename}"

        # Decide on directory: prefer tests/ unless file is in tests/ or a blueprint
        dirname = os.path.dirname(module_path).replace("\\", "/")
        if "tests" in dirname or dirname == "tests":
            return f"{dirname}/{filename}.py"
        elif dirname in ("api", "discord_bot", "runners", "commands"):
            return f"{dirname}/{filename}.py"
        else:
            return f"tests/{filename}.py"

    # ── Detection ────────────────────────────────────────────────────────
    def _detect_test_type(self, description: str, output: str) -> str:
        """
        Infer test pattern from description and output.

        Returns: "function", "class", "endpoint", "command", or "basic"
        """
        text = f"{description} {output}".lower()

        if self._ENDPOINT_RE.search(text):
            return "endpoint"
        if self._COMMAND_RE.search(text):
            return "command"
        if self._CLASS_RE.search(description):
            return "class"
        if self._FUNCTION_RE.search(description):
            return "function"

        return "basic"

    def _infer_test_structure(
        self,
        description: str,
        output: str,
        module_path: str,
        test_type: str,
    ) -> Tuple[str, List[str]]:
        """
        Infer test class name and list of test method names.

        Returns: (class_name, [method_names, ...])
        """
        # Extract candidate name from description, output, or module path
        candidate = ""
        for match in self._FUNCTION_RE.finditer(description):
            candidate = match.group(1)
            break
        if not candidate:
            for match in self._CLASS_RE.finditer(description):
                candidate = match.group(1)
                break
        if not candidate and module_path:
            candidate = os.path.basename(module_path).replace(".py", "")
        if not candidate:
            candidate = "generated"

        # Sanitize: only keep first word if multi-word (separated by underscore/hyphen)
        # to avoid "calculatetotal" from "calculate_total"
        first_word = candidate.split('_')[0].split('-')[0]
        if first_word:
            candidate = first_word

        # Sanitize: remove non-alphanumeric
        candidate = re.sub(r'[^a-zA-Z0-9]', '', candidate)
        if not candidate:
            candidate = "generated"

        # Build class name: "Test" + Candidate (capitalize first letter only)
        test_class = f"Test{candidate[0].upper() + candidate[1:] if len(candidate) > 1 else candidate.upper()}"

        # Generate method names based on test_type
        methods = self._suggest_test_methods(candidate.lower(), test_type)

        return test_class, methods

    def _suggest_test_methods(self, name: str, test_type: str) -> List[str]:
        """Suggest 2-3 test method names based on function/class name and type."""
        base = name.lower().replace("-", "_")

        if test_type == "endpoint":
            return [
                f"test_{base}_success",
                f"test_{base}_invalid_input",
                f"test_{base}_not_found",
            ]
        elif test_type == "command":
            return [
                f"test_{base}_runs_successfully",
                f"test_{base}_handles_errors",
            ]
        elif test_type == "class":
            return [
                f"test_{base}_init",
                f"test_{base}_main_method",
                f"test_{base}_edge_case",
            ]
        else:  # "function" or "basic"
            return [
                f"test_{base}_valid_input",
                f"test_{base}_edge_case",
            ]

    # ── Import generation ────────────────────────────────────────────────
    def _generate_imports(self, test_type: str, module_path: str) -> str:
        """Generate import statements based on test type."""
        lines = [
            "import unittest",
            "from unittest.mock import patch, MagicMock",
        ]

        if test_type == "endpoint":
            lines.extend([
                "import json",
                "import sys",
                "from pathlib import Path",
            ])
        elif test_type == "command":
            lines.extend([
                "import subprocess",
                "import json",
            ])

        # Add import for the module being tested
        if module_path and module_path.endswith(".py"):
            # Convert file path to import path
            import_path = module_path.replace("\\", "/").replace("/", ".").replace(".py", "")
            lines.append(f"# from {import_path} import ...")

        return "\n".join(lines)

    # ── Test class generation ────────────────────────────────────────────
    def _generate_test_class(
        self,
        class_name: str,
        methods: List[str],
        test_type: str,
        module_path: str,
    ) -> str:
        """Generate full test class with setUp, tearDown, and test methods."""
        lines = [f"class {class_name}(unittest.TestCase):"]
        lines.append('    """Auto-generated test class."""')
        lines.append("")

        # Generate setUp if needed
        if test_type in ("endpoint", "command", "class"):
            lines.append("    def setUp(self):")
            if test_type == "endpoint":
                lines.append("        # from app import app")
                lines.append("        # self.app = app")
                lines.append("        # self.client = self.app.test_client()")
            elif test_type == "command":
                lines.append("        # Set up any fixtures or mocks")
                lines.append("        pass")
            elif test_type == "class":
                lines.append("        # Initialize test instance")
                lines.append("        pass")
            lines.append("")

        # Generate test methods
        for method_name in methods:
            lines.append(f"    def {method_name}(self):")
            if test_type == "endpoint":
                lines.append('        """Test endpoint behavior."""')
                lines.append("        # response = self.client.get('/api/endpoint')")
                lines.append("        # self.assertEqual(response.status_code, 200)")
            elif test_type == "command":
                lines.append('        """Test command execution."""')
                lines.append("        # result = subprocess.run(['command'], capture_output=True)")
                lines.append("        # self.assertEqual(result.returncode, 0)")
            elif test_type == "class":
                lines.append('        """Test class method."""')
                lines.append("        # instance = SomeClass()")
                lines.append("        # self.assertTrue(instance.method())")
            else:  # "function" or "basic"
                lines.append('        """Test function behavior."""')
                lines.append("        # result = some_function(arg)")
                lines.append("        # self.assertIsNotNone(result)")
            lines.append("")

        # Generate tearDown if needed
        if test_type in ("endpoint", "command", "class"):
            lines.append("    def tearDown(self):")
            if test_type == "endpoint":
                lines.append("        # Clean up Flask app state")
                lines.append("        pass")
            else:
                lines.append("        # Clean up test fixtures")
                lines.append("        pass")

        return "\n".join(lines)


# ── Module-level helpers ─────────────────────────────────────────────────────

def generate_test(
    description: str,
    output: str = "",
    module_path: str = "",
) -> str:
    """Convenience function to generate test code."""
    gen = SkeletonGenerator()
    return gen.generate_test(description, output, module_path)


def suggest_test_file(module_path: str) -> str:
    """Convenience function to suggest test file path."""
    gen = SkeletonGenerator()
    return gen.suggest_test_file(module_path)


# For backwards compatibility, alias TestGenerator to SkeletonGenerator
TestGenerator = SkeletonGenerator
