"""
Unit tests for agents/test_generator.py

Run:
    python -m pytest tests/test_test_generator.py -v --tb=short
"""

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from agents.test_generator import SkeletonGenerator, generate_test, suggest_test_file


class TestTestGeneratorSyntax(unittest.TestCase):
    """Verify generated test code is valid Python."""

    def setUp(self):
        self.gen = SkeletonGenerator()

    def test_generates_valid_python_syntax(self):
        """Generated code should be compilable Python."""
        code = self.gen.generate_test(
            "Create a function to parse JSON strings",
            "",
            "utils/parser.py",
        )
        # Try to compile; should not raise SyntaxError
        try:
            compile(code, "<generated>", "exec")
        except SyntaxError as e:
            self.fail(f"Generated code has syntax error: {e}")

    def test_basic_description_generates_valid_code(self):
        """Even minimal description should generate valid code."""
        code = generate_test("function to add numbers")
        try:
            compile(code, "<generated>", "exec")
        except SyntaxError as e:
            self.fail(f"Syntax error: {e}")

    def test_empty_description_generates_valid_code(self):
        """Even empty description should generate valid code."""
        code = self.gen.generate_test("")
        try:
            compile(code, "<generated>", "exec")
        except SyntaxError as e:
            self.fail(f"Syntax error: {e}")

    def test_generated_code_contains_auto_comment(self):
        """Generated code should start with auto-generated comment."""
        code = self.gen.generate_test("test function")
        self.assertIn("auto-generated by TestGenerator", code)
        self.assertTrue(code.startswith("# auto-generated"))

    def test_generated_code_contains_imports(self):
        """Generated code should include unittest import."""
        code = self.gen.generate_test("test function")
        self.assertIn("import unittest", code)

    def test_generated_code_ends_with_newline(self):
        """Generated code should end with newline."""
        code = self.gen.generate_test("test function")
        self.assertTrue(code.endswith("\n"))


class TestTestGeneratorClassNaming(unittest.TestCase):
    """Verify test class naming follows conventions."""

    def setUp(self):
        self.gen = SkeletonGenerator()

    def test_class_name_starts_with_test(self):
        """Test class name should start with 'Test'."""
        code = self.gen.generate_test("Create function foo_bar")
        self.assertIn("class Test", code)

    def test_class_name_follows_camelcase_convention(self):
        """Test class names should use CamelCase after 'Test'."""
        code = self.gen.generate_test("Create function parser")
        self.assertIn("class TestParser(unittest.TestCase):", code)

    def test_function_name_inferred_for_class_name(self):
        """Class name should be inferred from function/class name in description."""
        code = self.gen.generate_test("def calculate_total(items): ...")
        # Should use first word: "calculate" → "TestCalculate"
        self.assertRegex(code, r'class Test\w+\(unittest\.TestCase\):')

    def test_sanitizes_special_chars_in_class_name(self):
        """Special characters should be removed from class name."""
        code = self.gen.generate_test("Create function parse-json-data")
        # Should not have hyphens, should be CamelCase
        self.assertRegex(code, r'class Test\w+\(unittest\.TestCase\):')
        self.assertNotIn("parse-json", code.lower())

    def test_method_names_follow_test_convention(self):
        """Test method names should start with 'test_'."""
        code = self.gen.generate_test("Create function process")
        # Count test_ methods
        import re
        methods = re.findall(r'def (test_\w+)\(self\):', code)
        self.assertGreaterEqual(len(methods), 2)

    def test_method_names_are_descriptive(self):
        """Test method names should describe what is being tested."""
        code = self.gen.generate_test("function to validate email")
        self.assertRegex(code, r'def test_\w+\(self\):')


class TestTestGeneratorDetection(unittest.TestCase):
    """Test pattern detection logic."""

    def setUp(self):
        self.gen = SkeletonGenerator()

    def test_detects_function_pattern(self):
        """Should detect function pattern from description."""
        test_type = self.gen._detect_test_type(
            "Create a function to parse JSON",
            "",
        )
        self.assertEqual(test_type, "function")

    def test_detects_class_pattern(self):
        """Should detect class pattern from description."""
        test_type = self.gen._detect_test_type(
            "Implement a class for managing tasks",
            "",
        )
        self.assertEqual(test_type, "class")

    def test_detects_endpoint_pattern_from_output(self):
        """Should detect API endpoint pattern from output."""
        test_type = self.gen._detect_test_type(
            "Create an API",
            "Added GET /api/tasks endpoint",
        )
        self.assertEqual(test_type, "endpoint")

    def test_detects_command_pattern(self):
        """Should detect CLI command pattern."""
        test_type = self.gen._detect_test_type(
            "Add a --verbose flag",
            "",
        )
        self.assertEqual(test_type, "command")

    def test_defaults_to_basic_pattern(self):
        """Should default to 'basic' for ambiguous descriptions."""
        test_type = self.gen._detect_test_type(
            "Fix a bug in the system",
            "",
        )
        self.assertEqual(test_type, "basic")


class TestTestGeneratorEndpoints(unittest.TestCase):
    """Test API endpoint test generation."""

    def setUp(self):
        self.gen = SkeletonGenerator()

    def test_endpoint_test_includes_flask_import(self):
        """Endpoint tests should hint at Flask test client."""
        code = self.gen.generate_test(
            "Create GET /api/health endpoint",
            "Added GET /api/health endpoint",
        )
        # Should include hints about test_client
        self.assertIn("test_client", code)

    def test_endpoint_test_includes_setUp(self):
        """Endpoint tests should have setUp for app initialization."""
        code = self.gen.generate_test(
            "Create POST /api/tasks endpoint",
            "POST /api/tasks returns 201",
        )
        self.assertIn("def setUp(self):", code)

    def test_endpoint_test_includes_status_code_check(self):
        """Endpoint tests should check status codes."""
        code = self.gen.generate_test(
            "GET /api/data endpoint",
            "response: 200 OK",
        )
        self.assertIn("status_code", code)

    def test_endpoint_test_has_multiple_methods(self):
        """Endpoint tests should suggest success, error, and not_found cases."""
        code = self.gen.generate_test(
            "GET /api/users/{id}",
            "",
        )
        # Should have at least 3 test methods for endpoints
        import re
        methods = re.findall(r'def (test_\w+)\(self\):', code)
        self.assertGreaterEqual(len(methods), 2)


class TestTestGeneratorCommands(unittest.TestCase):
    """Test CLI command test generation."""

    def setUp(self):
        self.gen = SkeletonGenerator()

    def test_command_test_includes_subprocess(self):
        """Command tests should include subprocess import."""
        code = self.gen.generate_test(
            "Add --output-format json flag",
            "subprocess run",
        )
        self.assertIn("import subprocess", code)

    def test_command_test_includes_setUp(self):
        """Command tests should have setUp."""
        code = self.gen.generate_test(
            "Create CLI command for backup",
            "",
        )
        self.assertIn("def setUp(self):", code)

    def test_command_test_checks_return_code(self):
        """Command tests should check returncode."""
        code = self.gen.generate_test(
            "command to validate input",
            "subprocess",
        )
        self.assertIn("returncode", code)


class TestTestGeneratorFilePath(unittest.TestCase):
    """Test test file path suggestion."""

    def setUp(self):
        self.gen = SkeletonGenerator()

    def test_suggests_test_directory_for_utils(self):
        """Utils modules should suggest tests/ directory."""
        path = self.gen.suggest_test_file("utils/parser.py")
        # Normalize path separators
        path = path.replace("\\", "/")
        self.assertEqual(path, "tests/test_parser.py")

    def test_suggests_same_directory_for_api(self):
        """API modules should suggest same directory (e.g., api/test_app.py)."""
        path = self.gen.suggest_test_file("api/app.py")
        path = path.replace("\\", "/")
        self.assertEqual(path, "api/test_app.py")

    def test_suggests_same_directory_for_discord_bot(self):
        """Discord bot modules should stay in discord_bot/."""
        path = self.gen.suggest_test_file("discord_bot/bot.py")
        path = path.replace("\\", "/")
        self.assertEqual(path, "discord_bot/test_bot.py")

    def test_avoids_double_test_prefix(self):
        """Should not create test_test_ names."""
        path = self.gen.suggest_test_file("api/test_app.py")
        path = path.replace("\\", "/")
        self.assertEqual(path, "api/test_app.py")
        self.assertNotIn("test_test_", path)

    def test_converts_py_extension(self):
        """Should handle .py extension properly."""
        path = self.gen.suggest_test_file("utils/helper.py")
        self.assertTrue(path.endswith(".py"))
        self.assertNotIn(".py.py", path)

    def test_handles_empty_module_path(self):
        """Should handle empty module path gracefully."""
        path = self.gen.suggest_test_file("")
        self.assertTrue(path.endswith(".py"))
        self.assertIn("test_", path)

    def test_handles_none_module_path(self):
        """Should handle None module path gracefully."""
        path = self.gen.suggest_test_file(None)
        self.assertTrue(path.endswith(".py"))

    def test_extracts_filename_from_deep_path(self):
        """Should extract filename from deep directory paths."""
        path = self.gen.suggest_test_file("src/lib/utils/math_helper.py")
        self.assertIn("test_math_helper.py", path)


class TestTestGeneratorEdgeCases(unittest.TestCase):
    """Test edge cases and error handling."""

    def setUp(self):
        self.gen = SkeletonGenerator()

    def test_handles_none_description(self):
        """Should handle None description without crashing."""
        code = self.gen.generate_test(None, "", "")
        self.assertIsInstance(code, str)
        self.assertGreater(len(code), 0)

    def test_handles_none_output(self):
        """Should handle None output without crashing."""
        code = self.gen.generate_test("test", None, "")
        self.assertIsInstance(code, str)

    def test_handles_none_module_path(self):
        """Should handle None module_path without crashing."""
        code = self.gen.generate_test("test", "output", None)
        self.assertIsInstance(code, str)

    def test_handles_whitespace_only_description(self):
        """Should handle whitespace-only description."""
        code = self.gen.generate_test("   \n  \t  ", "", "")
        self.assertIsInstance(code, str)
        try:
            compile(code, "<generated>", "exec")
        except SyntaxError as e:
            self.fail(f"Whitespace-only input generated syntax error: {e}")

    def test_handles_very_long_description(self):
        """Should handle very long descriptions."""
        long_desc = "Create a function to " * 100 + "process data"
        code = self.gen.generate_test(long_desc, "", "")
        self.assertIsInstance(code, str)
        try:
            compile(code, "<generated>", "exec")
        except SyntaxError as e:
            self.fail(f"Long description generated syntax error: {e}")

    def test_handles_special_characters_in_description(self):
        """Should handle special characters in description."""
        code = self.gen.generate_test(
            "Create function: test@#$%^&*()!<>?",
            "",
            "",
        )
        self.assertIsInstance(code, str)
        try:
            compile(code, "<generated>", "exec")
        except SyntaxError as e:
            self.fail(f"Special chars generated syntax error: {e}")


class TestTestGeneratorIntegration(unittest.TestCase):
    """Integration tests for typical workflows."""

    def setUp(self):
        self.gen = SkeletonGenerator()

    def test_complete_function_test_generation(self):
        """Full workflow: description + output → complete test file."""
        description = "Create a validate_email function"
        output = """
def validate_email(email: str) -> bool:
    \"\"\"Check if email is valid.\"\"\"
    return "@" in email
        """
        module_path = "utils/validators.py"

        code = self.gen.generate_test(description, output, module_path)
        test_file = self.gen.suggest_test_file(module_path)

        # Verify code structure
        self.assertIn("class Test", code)
        self.assertIn("def test_", code)
        self.assertIn("import unittest", code)

        # Verify file path (normalize separators)
        test_file_normalized = test_file.replace("\\", "/")
        self.assertIn("validators", test_file_normalized)
        self.assertIn("tests/", test_file_normalized)

        # Code should be valid
        try:
            compile(code, "<generated>", "exec")
        except SyntaxError as e:
            self.fail(f"Integration test generated invalid syntax: {e}")

    def test_api_endpoint_complete_workflow(self):
        """Full workflow for API endpoint test generation."""
        description = "Add a GET /api/tasks endpoint to list all tasks"
        output = "Added GET /api/tasks\nStatus: 200 OK\nReturns: [task1, task2]"
        module_path = "api/app.py"

        code = self.gen.generate_test(description, output, module_path)
        test_file = self.gen.suggest_test_file(module_path)

        # Should generate endpoint-style tests
        self.assertIn("test_client", code)
        self.assertIn("def setUp", code)
        self.assertIn("status_code", code)

        # File path should be api/test_app.py (normalize separators)
        test_file_normalized = test_file.replace("\\", "/")
        self.assertEqual(test_file_normalized, "api/test_app.py")

    def test_cli_command_complete_workflow(self):
        """Full workflow for CLI command test generation."""
        description = "Add --dry-run flag to preview changes"
        output = "$ python cli.py --dry-run\npreview output"
        module_path = "solo_builder_cli.py"

        code = self.gen.generate_test(description, output, module_path)

        # Should include subprocess patterns
        self.assertIn("subprocess", code)
        self.assertIn("returncode", code)


class TestTestGeneratorConvenience(unittest.TestCase):
    """Test module-level convenience functions."""

    def test_module_level_generate_test(self):
        """Module-level generate_test function should work."""
        code = generate_test("Create a function")
        self.assertIsInstance(code, str)
        self.assertIn("class Test", code)

    def test_module_level_suggest_test_file(self):
        """Module-level suggest_test_file function should work."""
        path = suggest_test_file("utils/helper.py")
        self.assertIsInstance(path, str)
        self.assertIn("test_", path)


if __name__ == "__main__":
    unittest.main()
