"""
agents/test_generator.py
TestGenerator agent — automatically generates pytest tests for code produced
by the Executor.

Sits between Executor and Verifier in the step pipeline:
    … → Executor → PatchReviewer → **TestGenerator** → Verifier → …

Behaviour:
    1. Identify Python files referenced in Executor output.
    2. Ask Claude (Anthropic SDK) to generate pytest tests.
    3. Save generated tests in tests/generated/.
"""

import os
import re
from typing import Any, Dict, List, Tuple

from utils.helper_functions import (
    CYAN, DIM, GREEN, RED, RESET, YELLOW,
    add_memory_snapshot,
)

# ── Prompt template ──────────────────────────────────────────────────────────
_TEST_GEN_PROMPT = """\
You are a Python test engineer. Generate pytest tests for the following code.

## Task description
{description}

## Code / Executor output
{output}

## Rules
- Write valid pytest tests (functions prefixed with test_).
- Import any necessary modules; use relative imports if needed.
- Include at least 2 test functions.
- Cover the main logic and at least one edge case.
- Do NOT include markdown fences — output raw Python only.
- Add "# auto-generated by TestGenerator" as the first comment line.
"""


class TestGenerator:
    """
    Generates pytest test files for code produced by the Executor.

    After each step, inspects subtask output for Python file references or
    code content.  For qualifying subtasks, asks Claude to generate tests
    and writes them to ``tests/generated/``.

    Configurable via settings keys:
        TEST_GENERATOR_ENABLED     (bool, default True)
        TEST_GENERATOR_MODEL       (str,  default from ANTHROPIC_MODEL)
        TEST_GENERATOR_MAX_TOKENS  (int,  default 1024)
        TEST_GENERATOR_OUTPUT_DIR  (str,  default "tests/generated")
    """

    # Patterns that indicate Python file involvement
    _PY_FILE_RE = re.compile(r'[\w/\\.-]+\.py\b')
    _CODE_INDICATORS = re.compile(
        r'(?:^|\n)\s*(?:def |class |import |from .+ import )', re.MULTILINE
    )

    def __init__(self, settings: Dict[str, Any] | None = None) -> None:
        cfg = settings or {}
        self.enabled     = cfg.get("TEST_GENERATOR_ENABLED", True)
        self._model      = cfg.get("TEST_GENERATOR_MODEL",
                                   cfg.get("ANTHROPIC_MODEL", "claude-sonnet-4-6"))
        self._max_tokens = cfg.get("TEST_GENERATOR_MAX_TOKENS", 1024)
        self._root       = cfg.get("TEST_GENERATOR_ROOT", os.path.dirname(
            os.path.dirname(os.path.abspath(__file__))
        ))
        self._output_dir = os.path.join(
            self._root,
            cfg.get("TEST_GENERATOR_OUTPUT_DIR", "tests/generated"),
        )
        self.max_test_gens_per_step = cfg.get("MAX_TEST_GENERATIONS_PER_STEP", 0)
        self._client     = None
        self.available   = self._init_client()
        self._generated: set = set()  # track subtasks already handled

    def _init_client(self) -> bool:
        if not self.enabled:
            return False
        try:
            import anthropic  # noqa: PLC0415
            key = os.environ.get("ANTHROPIC_API_KEY", "")
            if not key:
                return False
            self._client = anthropic.Anthropic(api_key=key)
            return True
        except ImportError:
            return False

    # ── Public API ───────────────────────────────────────────────────────
    def generate_tests(
        self,
        dag: Dict,
        executor_actions: Dict[str, str],
        step: int,
        memory_store: Dict,
        alerts: List[str],
        budget=None,
    ) -> int:
        """
        Scan Executor results for Python code and generate tests.

        Returns the number of test files written.
        """
        if not self.available:
            return 0

        written = 0
        gens_this_step = 0

        for task_name, task_data in dag.items():
            for branch_name, branch_data in task_data.get("branches", {}).items():
                for st_name, st_data in branch_data.get("subtasks", {}).items():
                    if st_name not in executor_actions:
                        continue
                    action = executor_actions[st_name]
                    if action not in ("verified", "review"):
                        continue
                    if st_name in self._generated:
                        continue

                    output      = st_data.get("output", "").strip()
                    description = st_data.get("description", "").strip()

                    if not self._has_python_content(output):
                        continue

                    # Throughput cap: defer excess generations
                    if (self.max_test_gens_per_step > 0
                            and gens_this_step >= self.max_test_gens_per_step):
                        alerts.append(
                            f"  {YELLOW}[TestGenerator]{RESET} "
                            f"{CYAN}{st_name}{RESET} deferred (throughput cap)"
                        )
                        continue

                    # Check AI budget — fail-safe: do NOT skip silently
                    if budget is not None and budget.exhausted:
                        alerts.append(
                            f"  {YELLOW}[TestGenerator]{RESET} "
                            f"{CYAN}{st_name}{RESET} deferred (budget exhausted)"
                        )
                        continue

                    test_code, usage_tokens = self._ask_claude(description, output)

                    gens_this_step += 1
                    if budget is not None:
                        budget.consume(1)
                        budget.record_usage(
                            tokens=usage_tokens, agent="TestGenerator",
                        )
                    if not test_code:
                        continue

                    path = self._write_test_file(st_name, test_code, step)
                    if path:
                        self._generated.add(st_name)
                        written += 1
                        add_memory_snapshot(
                            memory_store, branch_name,
                            f"{st_name}_tests_generated", step,
                        )
                        rel = os.path.relpath(path, self._root)
                        alerts.append(
                            f"  {GREEN}[TestGenerator]{RESET} "
                            f"wrote {CYAN}{rel}{RESET} for {st_name}"
                        )

        return written

    # ── Detection ────────────────────────────────────────────────────────
    def _has_python_content(self, output: str) -> bool:
        """Return True if the output references .py files or contains Python code."""
        if not output:
            return False
        if self._PY_FILE_RE.search(output):
            return True
        if self._CODE_INDICATORS.search(output):
            return True
        return False

    def extract_py_files(self, output: str) -> List[str]:
        """Extract .py file paths referenced in executor output."""
        return list(dict.fromkeys(self._PY_FILE_RE.findall(output)))

    # ── Claude interaction ───────────────────────────────────────────────
    def _ask_claude(self, description: str, output: str) -> Tuple[str, int]:
        """Ask Claude to generate pytest tests. Returns (raw_python, usage_tokens)."""
        prompt = _TEST_GEN_PROMPT.format(
            description=description or "(no description)",
            output=output or "(empty output)",
        )
        try:
            msg = self._client.messages.create(
                model=self._model,
                max_tokens=self._max_tokens,
                messages=[{"role": "user", "content": prompt}],
            )
            reply = msg.content[0].text.strip()
            usage_tokens = getattr(msg.usage, "input_tokens", 0) + \
                           getattr(msg.usage, "output_tokens", 0)
        except Exception:
            return "", 0

        # Strip markdown fences if Claude included them despite instructions
        reply = self._strip_fences(reply)
        return reply, usage_tokens

    @staticmethod
    def _strip_fences(text: str) -> str:
        """Remove ```python ... ``` wrappers if present."""
        stripped = text.strip()
        if stripped.startswith("```"):
            lines = stripped.split("\n")
            # Remove first line (```python) and last line (```)
            if lines[-1].strip() == "```":
                lines = lines[1:-1]
            else:
                lines = lines[1:]
            return "\n".join(lines)
        return stripped

    # ── File writing ─────────────────────────────────────────────────────
    def _write_test_file(self, st_name: str, test_code: str, step: int) -> str:
        """
        Write generated test code to tests/generated/.

        Returns the file path on success, '' on failure.
        """
        os.makedirs(self._output_dir, exist_ok=True)

        # Sanitise subtask name for filename: A1 → test_a1.py
        safe = re.sub(r'[^a-zA-Z0-9]', '_', st_name).lower()
        filename = f"test_{safe}_step{step}.py"
        path = os.path.join(self._output_dir, filename)

        try:
            with open(path, "w", encoding="utf-8") as f:
                f.write(test_code)
                if not test_code.endswith("\n"):
                    f.write("\n")
            return path
        except OSError:
            return ""
