[CmdletBinding()]
param()
$ErrorActionPreference = 'Stop'

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$claudeDir = Join-Path $repoRoot 'claude'
$verifyPath = Join-Path $claudeDir 'VERIFY.json'
$reproPath = Join-Path $claudeDir 'REPRO.md'

function New-Cmd {
  param(
    [string]$Name,
    [string]$Command,
    [bool]$Required,
    [int]$TimeoutSec
  )
  [pscustomobject]@{
    name = $Name
    command = $Command
    required = $Required
    timeout_sec = $TimeoutSec
  }
}

$projectSignals = 0
$commands = New-Object System.Collections.Generic.List[object]

$packageJson = Join-Path $repoRoot 'package.json'
if (Test-Path $packageJson) {
  $pkg = Get-Content -Raw -Path $packageJson | ConvertFrom-Json
  $commands.Add((New-Cmd -Name 'npm-install' -Command 'npm install' -Required $true -TimeoutSec 900)) | Out-Null
  $projectSignals++
  if ($pkg.scripts) {
    foreach ($name in @('lint', 'test', 'build', 'e2e')) {
      if ($pkg.scripts.PSObject.Properties.Name -contains $name) {
        $commands.Add((New-Cmd -Name ("npm-$name") -Command ("npm run $name") -Required $true -TimeoutSec 900)) | Out-Null
      }
    }
  }
}

$playwrightSignals = @('playwright.config.ts', 'playwright.config.js', 'playwright.config.mjs')
if (($playwrightSignals | ForEach-Object { Test-Path (Join-Path $repoRoot $_) }) -contains $true) {
  $commands.Add((New-Cmd -Name 'playwright-test' -Command 'npx playwright test' -Required $false -TimeoutSec 1200)) | Out-Null
  $projectSignals++
}

$pythonSignals = @('pyproject.toml', 'requirements.txt', 'setup.py', 'tox.ini')
$hasPython = (($pythonSignals | ForEach-Object { Test-Path (Join-Path $repoRoot $_) }) -contains $true) -or (Test-Path (Join-Path $repoRoot 'tests'))
if ($hasPython) {
  $usePytest = (Test-Path (Join-Path $repoRoot 'pytest.ini'))
  $pyproject = Join-Path $repoRoot 'pyproject.toml'
  if (Test-Path $pyproject) {
    $pyprojectText = Get-Content -Raw -Path $pyproject
    if ($pyprojectText -match 'pytest') { $usePytest = $true }
  }
  if ($usePytest) {
    $commands.Add((New-Cmd -Name 'pytest' -Command 'pytest' -Required $false -TimeoutSec 900)) | Out-Null
  } else {
    $commands.Add((New-Cmd -Name 'unittest-discover' -Command 'python -m unittest discover' -Required $false -TimeoutSec 900)) | Out-Null
  }
  $projectSignals++
}

if ($projectSignals -eq 0) {
  $failCmd = "powershell -NoProfile -ExecutionPolicy Bypass -Command `"Write-Error 'No project verification commands detected. Add scripts/tests, then rerun tools/bootstrap_verify.ps1.'; exit 1`""
  $commands.Add((New-Cmd -Name 'no-verification-detected' -Command $failCmd -Required $true -TimeoutSec 30)) | Out-Null
}

$commands.Add((New-Cmd -Name 'git-status' -Command 'git status --short --branch' -Required $true -TimeoutSec 60)) | Out-Null
$commands.Add((New-Cmd -Name 'git-diff-stat' -Command 'git diff --stat' -Required $true -TimeoutSec 60)) | Out-Null

$verify = [pscustomobject]@{
  version = 1
  generated_at = [DateTime]::UtcNow.ToString('o')
  commands = $commands
  notes = 'Generated by tools/bootstrap_verify.ps1'
}
$verify | ConvertTo-Json -Depth 8 | Set-Content -Path $verifyPath -Encoding UTF8

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('# Repro Steps') | Out-Null
$lines.Add('') | Out-Null
$lines.Add('Generated by `tools/bootstrap_verify.ps1`. Run commands in order:') | Out-Null
$i = 1
foreach ($c in $commands) {
  $requiredText = if ($c.required) { 'required' } else { 'optional' }
  $lines.Add("$i. [$requiredText] ``$($c.command)``") | Out-Null
  $i++
}
$lines -join "`r`n" | Set-Content -Path $reproPath -Encoding UTF8

Write-Host "Wrote $verifyPath and $reproPath"
